modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
[[mods]]
modId="casualness_delight"
version="1.20.1-0.4n"
displayName="Casualness Delight"
logoFile="logo.png"
logoBlur=false
authors="TsukimiRen"
description='''An addon mod for Farmer's Delight'''
[[dependencies.casualness_delight]]
   modId="forge"
   mandatory=true
   versionRange="[47.1,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.casualness_delight]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20,1.21)"
   ordering="NONE"
   side="BOTH"
[[dependencies.casualness_delight]]
modId="farmersdelight"
mandatory=true
versionRange="*"
ordering="AFTER"
side="BOTH"
